/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;

/**
 *
 * @author hwarn
 */
public class StockGUI extends javax.swing.JFrame {

    /**
     * Creates new form StockGUI
     */
    public StockGUI() {
        initComponents();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_Stock = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField_ProductID = new javax.swing.JTextField();
        textField_Quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textField_StoreID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_Stock.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                stockListSelected(evt);
            }
        });
        jScrollPane1.setViewportView(list_Stock);

        jLabel1.setText("Stock Table");

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonPressed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonPressed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonPressed(evt);
            }
        });

        jLabel2.setText("Product ID :");

        jLabel3.setText("Quantity:");

        jLabel4.setText("Store ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_ProductID)
                            .addComponent(textField_Quantity)
                            .addComponent(textField_StoreID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textField_StoreID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textField_ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textField_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonPressed
        // TODO add your handling code here:
        try {

        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/teamaproject", "root","");

        Statement staDelete = connection.createStatement();


        String queryDelete = 
                "DELETE FROM stock WHERE store_id = " + textField_StoreID.getText() +
                " and product_id = " + textField_ProductID.getText();

                        
        staDelete.executeUpdate(queryDelete);
       
        connection.close();

        } catch (Exception exception) { //catch any exceptions that may have occured

            exception.printStackTrace(); //print any errors

        }
        refresh();
    }//GEN-LAST:event_deleteButtonPressed

    private void newButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonPressed
 
        try{

           Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/teamaproject", "root","");
           Statement insert = connection.createStatement();
           
           String queryInsert = "INSERT INTO stock " + "VALUES("
                   + textField_StoreID.getText() + ","
                   + textField_ProductID.getText() + ","
                   + textField_Quantity.getText() + ")";
           

           

           insert.executeUpdate(queryInsert);
           
           connection.close();

           
        } catch (Exception exception) {
            exception.printStackTrace();
        } 
        
        refresh();
        
        
    }//GEN-LAST:event_newButtonPressed

    private void updateButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonPressed
      
        try {

        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/teamaproject", "root","");

        Statement staUpdate = connection.createStatement();


        String queryUpdate = 
                "UPDATE stock SET " 
                + "Quantity = '" + textField_Quantity.getText()
                + "' WHERE store_id = " + textField_StoreID.getText()
                + " and product_id = " + textField_ProductID.getText();

                        
        staUpdate.executeUpdate(queryUpdate);
       
        connection.close();

        } catch (Exception exception) { //catch any exceptions that may have occured

            exception.printStackTrace(); //print any errors

        }
        
        
    }//GEN-LAST:event_updateButtonPressed

    private void stockListSelected(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_stockListSelected
        // TODO add your handling code here:
        int index = list_Stock.getSelectedIndex();
        if(index < 0){return;}


        //get the cpk (store_id, product_id)

        String s = (String) list_Stock.getSelectedValue();
        
        String[] parts = s.split(" ");
        
        String store_id = parts[2];
        String product_id = parts[6];
          
        

        System.out.println(store_id + product_id);

        //Call the update form funciton to update the screen
        updateform(store_id, product_id);
    }//GEN-LAST:event_stockListSelected
    
    public void updateform(String store_id, String product_id){

        try {

        //Establish mysql connection

        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/teamaproject", "root","");

        //Initialize the query

        String query = 
                "select * from stock where store_id = " + store_id +
                " and product_id = " + product_id;

        //create the statement

        Statement sta = connection.createStatement();

        //Set the results

        ResultSet rs = sta.executeQuery(query);

        //Because we are targeting a primary key, we simply set the values to the results taht are retrieved.

        rs.next();
        //Set the controls to the dtabase values
        //textField_User.setText(rs.getString("ID"));

        textField_StoreID.setText(rs.getString("store_id"));
        textField_ProductID.setText(rs.getString("product_id"));
        textField_Quantity.setText(rs.getString("quantity"));


        //close the connection

        connection.close();

        } catch (Exception exception) { //catch any exceptions that may have occured

            exception.printStackTrace(); //print any errors

        }

    }
    
    public void refresh(){

        try {

            //Connect to the database

            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/teamaproject", "root","");

            //initialize the query

            String query = "select * from stock order by store_id";

            //Create a new statement

            Statement sta = connection.createStatement();

            //Execute the Query and assign the results to the rs object

            ResultSet rs = sta.executeQuery(query);

            //instantiate a new DefaultListModel

            DefaultListModel listModel;

            listModel = new DefaultListModel();

            //Loop through the results and add the items to the lsit model

            while (rs.next()) {

                listModel.addElement(
                        "Store id: " + rs.getString("store_id") + " - " +
                        "Product id: " + rs.getString("product_id"));

            }

            //Set the model of the userList to the list Model

            list_Stock.setModel(listModel);

            //Close the connection

            connection.close();

            //Catch any errors

        } catch (Exception exception) {

            exception.printStackTrace();

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_Stock;
    private javax.swing.JTextField textField_ProductID;
    private javax.swing.JTextField textField_Quantity;
    private javax.swing.JTextField textField_StoreID;
    // End of variables declaration//GEN-END:variables
}
